### ISSUE TITLE
La linea Prueba.java#L3 está mal redactada.

### ISSUE THREAD

**Issue by Enriquepg013** [iesgrancapitan-1DAMB-2223-ED/tareagit38-Enriquepg013#1]

**Comment by Enriquepg013** [comment]
public class  Prueba {
  public static void main(String[] args) {
    Sistem.out.println("Hola Mundo!");
  }
}

**Comment by PeepoEvil** [comment]
public class Prueba {
public static void main(String[] args) {
System.out.println("Hola Mundo!");
}
}
